### ISSUE TITLE
Condiciones de finalización del juego

### ISSUE THREAD

**Issue by Lupama2** [IBProgramacionAvanzada/IBProgramAvanzada_Final_Grupo2#11]
Las condiciones para que se termine el juego son:
1. La bolita queda debajo de la barra (esto está mal implementado en el código)
2. No hay más bloques para romper

¿Deberíamos agregar la posibilidad de que si el usuario aprieta, por ejemplo, la letra "Q" se termine el juego tmb?

**Comment by Lupama2** [comment]
Creo que también deberíamos agregar en cada caso un "mensaje" de por qué se termina el juego. No se va a imprimir en pantalla, pero quizás podríamos crear una discriminated union que describa por qué caso particular finalizó el juego. Me explico?

**Comment by adosil1** [comment]
Me parece que sería mejor para la experiencia de juego perder cuando la bola toca el suelo y no justo cuando queda debajo de la barra porque esta tiene cierta elevación, si no se sentiría raro.
 
En cuanto a lo de abortar el juego con una tecla, creo que eso entra en la parte de interacciones que no debemos implementar como la opción de reiniciar, jugar de nuevo y cosas por el estilo.

**Comment by Lupama2** [comment]
Claro. Me parece perfecto
