### ISSUE TITLE
Definimos tipo tablero?

### ISSUE THREAD

**Issue by Lupama2** [IBProgramacionAvanzada/IBProgramAvanzada_Final_Grupo2#9]
Dado que tenemos bastantes objetos: bolita, paredes, barra, bloques, puntaje, ..., deberíamos definir un record "Tablero" que guarde toda la información del juego?

**Comment by adosil1** [comment]
Si, creo que estaría bueno!

**Comment by Lupama2** [comment]
Listo. Ahí lo definí
